server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    types { text/html html; text/plain md; image/svg+xml svg; text/css css; application/javascript js; }
    add_header X-Content-Type-Options nosniff;
    location / { try_files $uri $uri/ =404; }
}
